### ISSUE TITLE
Features not worked for build command in examples\edhoc-rs-no_std on system Windows

### ISSUE THREAD

**Issue by ysong02** [openwsn-berkeley/edhoc-rs#111]
Failed to build for crypto-psa and crypto-cryptocell310 in Windows environment.

**Comment by malishav** [comment]
@ysong02 could you update hte issue with the exact output of the build command that you get? thanks!

**Comment by ysong02** [comment]
<img width="946" alt="image" src="https://github.com/openwsn-berkeley/edhoc-rs/assets/71662449/5ecbe2a6-8c91-43ee-b010-8eecafc22334">
for software

**Comment by ysong02** [comment]
<img width="948" alt="image" src="https://github.com/openwsn-berkeley/edhoc-rs/assets/71662449/90439e30-f927-4f2d-b4f6-de89a8a3757b">
for hardware

**Comment by ysong02** [comment]
Solved build problem with cryptocell310 cryptographic backend by installing LLVM on Windows machine, and set LIBCLANG_PATH as an environment variable pointing to the bin directory of the LLVM install.

**Comment by geonnave** [comment]
So is this fixed now? If yes feel free to close it @ysong02.

**Comment by ysong02** [comment]
Still failed to build by psa crypto on Windows, the hardware one worked.
